-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE users
-- RENAME COLUMN name TO first_name;
--
-- ALTER TABLE users
-- ADD COLUMN last_name VARCHAR(255);
