-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE users
-- ALTER COLUMN last_name TYPE TEXT,
-- ALTER COLUMN first_name DROP NOT NULL,
-- ALTER COLUMN last_name DROP NOT NULL;
