-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP FUNCTION IF EXISTS public.get_nearby_appointments(double precision, double precision, double precision, timestamp without time zone, integer);
